name: Deploy to heroku

# on:
#   workflow_run:
#     workflows: ["Tests"]
#     branches: [main]
#     types:
#       - completed

on:
  push:
    branches:
      - main

jobs:
  build:
    # Se corre si el workflow Tests concluyo con existo
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}

          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          dockerfile_directory: ./

          dockerfile_name: Dockerfile

          # Additional options of docker build command.
          docker_options: "--no-cache"

          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web
